global:
  scrape_interval: 15s

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        
  # Create a job for Docker daemon.
  #
  # This example requires Docker daemon to be configured to expose
  # Prometheus metrics, as documented here:
  # https://docs.docker.com/config/daemon/prometheus/
  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"]
        
#  - job_name: 'static-hosts'
#    static_configs:
#      - targets: ['pbm-host:80']

  # dynamic docker containers
  # __address__="172.18.0.5:80"
  #__meta_docker_container_id="62cc7723c8409ef8b42545f6a3dadf8d1a12447ab42be7c8072da745ce4dff80"
  #__meta_docker_container_label_com_docker_compose_config_hash="d137a8e8bf4a976a1aea6caf00b7e703a6fa7ab6d7e82e58b496fba179370082"
  #__meta_docker_container_label_com_docker_compose_container_number="3"
  #__meta_docker_container_label_com_docker_compose_depends_on="azurite:service_started,jaeger:service_started"
  #__meta_docker_container_label_com_docker_compose_image="sha256:d7b88b0553c05bfed9a680baeb2556a1aabb68edef8d3ee1015b4594bf1e9022"
  #__meta_docker_container_label_com_docker_compose_oneoff="False"
  #__meta_docker_container_label_com_docker_compose_project="docker"
  #__meta_docker_container_label_com_docker_compose_service="matchingengine"
  #__meta_docker_container_label_com_docker_compose_version="2.15.1"
  #__meta_docker_container_label_org_opencontainers_image_created="2023-03-24T08:56:19.4224984Z"
  #__meta_docker_container_label_prometheus_port="80"
  #__meta_docker_container_label_prometheus_scrape="true"
  #__meta_docker_container_name="/docker-matchingengine-3"
  #__meta_docker_container_network_mode="docker_default"
  #__meta_docker_network_id="fc7d1583772d6474645c99020a35e2629e5f3740bf138dcc1f9c3095a133214a"
  #__meta_docker_network_ingress="false"
  #__meta_docker_network_internal="false"
  #__meta_docker_network_ip="172.18.0.5"
  #__meta_docker_network_label_com_docker_compose_network="default"
  #__meta_docker_network_label_com_docker_compose_project="docker"
  #__meta_docker_network_label_com_docker_compose_version="2.15.1"
  #__meta_docker_network_name="docker_default"
  #__meta_docker_network_scope="local"
  #__meta_docker_port_private="80"
  #__meta_docker_port_public="8083"
  #__meta_docker_port_public_ip="0.0.0.0"
  #__metrics_path__="/metrics"
  #__scheme__="http"
  #__scrape_interval__="15s"
  #__scrape_timeout__="10s"
  #job="matchingengine"
  - job_name: "services"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        action: keep
        regex: true
      - source_labels: [__address__]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)
        replacement: $1:80
      - source_labels: [__meta_docker_container_label_com_docker_compose_service,__meta_docker_container_label_com_docker_compose_container_number]
        action: replace
        target_label: "instance"
        regex: (.+);(\d+)
        replacement: ${1}-${2}      
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: "service_group"
      - source_labels: [__meta_docker_container_name]
        target_label: "service_instance"
